# Generated by Django 5.1.1 on 2024-09-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='timestamp',
            field=models.TextField(),
        ),
    ]
